### ISSUE TITLE
补充Nuclei Qemu里面 -M 和 -cpu 选项的一些更详细的文档

### ISSUE THREAD

**Issue by fanghuaqi** [Nuclei-Software/nuclei-tool-guide#6]
如题，当前的文档这一块比较薄弱，客户不知道如果不使用 SDK 或者 IDE怎么来传递对应的选项。

需要补充一个全命令行参数运行的里面每个参数的用途以及额外可以接受的参数及含义

**Comment by fanghuaqi** [comment]
例如 `qemu-system-riscv32 -M nuclei_evalsoc,download=ilm -cpu nuclei-n300fd,ext= -smp 1 -icount shift=0 -nodefaults -nographic -serial stdio -kernel dhrystone.elf` 这样的选项里面还可以补充那些描述

**Comment by bigmagic123** [comment]
qemu文档已经更新

**Comment by fanghuaqi** [comment]
已经进行了Review，请修改下

> qemu文档已经更新

**Comment by fanghuaqi** [comment]
Fixed by #7
